### ISSUE TITLE
Add the ability to use pattern jump commands in SDL_mixer

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL_mixer#118]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [Patch to add Mix_EnableModLooping to the api. Currently only available for mikmod replayed modules. (patch.diff, text/plain, 2012-06-15 08:27:38 +0000, 1791 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=878)

**Reported in version:** unspecified
**Reported for operating system, platform:** All, All

# Comments on the original bug report:

On 2012-06-15 08:27:38 +0000,  wrote:

> Created attachment 878
> Patch to add Mix_EnableModLooping to the api. Currently only available for mikmod replayed modules.
> 
> I'd really like control over whether pattern jump commands are allowed in a module. The current (sensible) default is, that these commands are not allowed and the module just ignores any pattern jump commands. But sometimes it is better to put multiple looping subsongs into one module and then just set the pattern to play with Mix_FadeInMusicPos et al. However currently with jump commands disabled all subsongs simply play one after the other.
> 
> I'd thus suggest adding something like Mix_EnableModLooping(Mix_Music *, enable) to the api which controls if pattern jump commands are allowed for a given module.
> 
> I supply a patch which does exactly that for modules played my the mikmod replayer code.

On 2017-10-21 22:22:55 +0000, Sam Lantinga wrote:

> I just switched the default to allow looping:
> https://hg.libsdl.org/SDL_mixer/rev/4359e193d93f
> 
> Does that fix your use case, or do you need it on sometimes and off other times?

**Comment by sezero** [comment]
No answer since 2017, closing.
