### ISSUE TITLE
Fluidsynth and libmodplug backend missing in Visual Studio Projects on Windows platform

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL_mixer#135]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.0
**Reported for operating system, platform:** Windows (All), x86

# Comments on the original bug report:

On 2013-06-09 10:14:22 +0000, RyanBram wrote:

> Based on issues tracker that I wrote in PySDL2 bitbucket (https://bitbucket.org/marcusva/py-sdl2/issue/2/add-support-for-fluidsynth-and-libmodplug), the author said that the VisualStudio projects for Win32 provided by official SDL2 release didn't support Fluidsynth and libmodplug by default.
> 
> Can SDL2 developer to enable it by default just like another library, such as Timidity or MikMod. Because based on my experience in with another software, Fluidsynth and libmodplug provide better implementation for MIDI and module format support.
> 
> Sorry for my English.

On 2017-10-21 22:09:43 +0000, Sam Lantinga wrote:

> I added libmodplug, but I haven't been able to build fluidsynth for Windows. If you've done it, you should just able to add MUSIC_MID_FLUIDSYNTH to the build flags and magically have fluidsynth support.
> 
> You'll need the latest Mercurial version of SDL_mixer for this:
> http://hg.libsdl.org/SDL_mixer

**Comment by sezero** [comment]
No reason to keep this open.
