### ISSUE TITLE
iOS project file brings other dependencies

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL_mixer#140]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [remove MODPLUG_MUSIC from ios project file (nomod.diff, application/octet-stream, 2013-07-25 16:41:59 +0000, 612 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=1254)

**Reported in version:** unspecified
**Reported for operating system, platform:** iOS 4, x86

# Comments on the original bug report:

On 2013-07-25 16:41:59 +0000, Vittorio Giovara wrote:

> Created attachment 1254
> remove MODPLUG_MUSIC from ios project file
> 
> I've compiled stock SDL_mixer project file and compiled every source fine.
> However when I link the resulting library, I get a lot of undefined symbols from modplug dep:
> 
> 
> Undefined symbols:
>   "operator new[](unsigned long)", referenced from:
>       CSoundFile::AllocatePattern(unsigned int, unsigned int)in libSDL2_mixer.a(sndfile.o)
> [cut]
>       AMSUnpack(char const*, unsigned int, char*, unsigned int, char)in libSDL2_mixer.a(load_ams.o)
>   "operator delete(void*)", referenced from:
>       _ModPlug_Unload in libSDL2_mixer.a(modplug.o)
>       _ModPlug_Load in libSDL2_mixer.a(modplug.o)
>       _ModPlug_Load in libSDL2_mixer.a(modplug.o)
>       CSoundFile::Destroy()      in libSDL2_mixer.a(sndfile.o)
>   "___gxx_personality_v0", referenced from:
>       ___gxx_personality_v0$non_lazy_ptr in libSDL2_mixer.a(modplug.o)
> [cut]
>      (maybe you meant: ___gxx_personality_v0$non_lazy_ptr)
> ld: symbol(s) not found
> collect2: ld returned 1 exit status
> 
> 
> Removing MODPLUG_MUSIC macro lets SDL_mixer be built and linked fine.
> Attached the patch for this, but not sure if it's the intended fix.

On 2013-07-27 04:23:47 +0000, Sam Lantinga wrote:

> That's a good point, it looks like the modplug code is C++.
> I'd like to avoid completely removing it from SDL_mixer for iOS.
> I'm leaving this open for now.

**Comment by slouken** [comment]
We now build libmodplug as a framework, which solves this issue.
