### ISSUE TITLE
Crash on load of 96000hz .wav

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL_mixer#157]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 1.2.12
**Reported for operating system, platform:** Mac OS X 10.8, x86_64

# Comments on the original bug report:

On 2014-01-27 04:04:49 +0000, manutoo wrote:

> Mix_LoadWAV_RW crashes when trying to load a .wav whose frequency is 96000hz on Max OSX 10.8 .
> Using SDL_mixer 1.2.11 instead of 1.2.12 avoid the crash.
> 
> Crash detail :
> Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
> 0   libsystem_kernel.dylib        	0x96f28a6a __pthread_kill + 10
> 1   libsystem_c.dylib             	0x98c64acf pthread_kill + 101
> 2   libsystem_c.dylib             	0x98c9b4f8 abort + 168
> 3   libsystem_c.dylib             	0x98c7dda3 free + 428
> 4   SDL                           	0x00c8e654 0xc87000 + 30292
> 5   org.libsdl.SDL-mixer          	0x00c35087 Mix_LoadWAV_RW + 128

**Comment by sezero** [comment]
Has anyone reproduced this?

**Comment by sezero** [comment]
Haven't try on a mac. But on Linux (CentOS 6.10 with default installation
of SDL-1.2.14 and SDL_mixer-1.2.12), a wav converted to 96 kHz using sox
and attempted playback using playmus doesn't crash for me.

**Comment by slouken** [comment]
Please attach a sample file and reopen this issue if you're still seeing a problem.
