### ISSUE TITLE
SDL_Mixer freezes any program if fadeout is followed by play

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL_mixer#165]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.0
**Reported for operating system, platform:** Windows (XP), x86

# Comments on the original bug report:

On 2014-05-17 04:37:04 +0000,  wrote:

> According to the documentation, if a fadeout is applied to a playing music stream, and then a new music file is played, Mixer will wait until the first stream has finished fading out before playing the second.
> 
> This is correct.
> 
> However it also freezes all program activity while it fades out.
> 
> This does not occur if the fadeout is not followed by a play, or if the second stream of music is played without fading out the first.

On 2014-05-17 04:37:50 +0000,  wrote:

> (mingw32, x86, GCC, 4.8).

On 2016-01-22 03:19:47 +0000,  wrote:

> Resolved as of sdl 2.04

On 2016-01-22 03:20:33 +0000,  wrote:

> Sorry, accidentally closed this - still active. Mistook for another bug.

**Comment by slouken** [comment]
I believe this is fixed for the latest release.
