### ISSUE TITLE
[PATCH] Add 'Libs.private' field to pkg-config file

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL_mixer#211]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [Patch to add 'Libs.private' field to pkg-config file (static-linking-fix.patch, text/plain, 2016-03-01 01:50:35 +0000, 1438 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=2388)

**Reported in version:** 1.2.12
**Reported for operating system, platform:** All, All

# Comments on the original bug report:

On 2016-03-01 01:50:35 +0000, Rodrigo Rebello wrote:

> Created attachment 2388
> Patch to add 'Libs.private' field to pkg-config file
> 
> In order to support static linking, SDL_mixer.pc should include a 'Libs.private' field listing all the libraries that SDL_mixer requires. This patch adds such a field.

On 2016-03-01 04:35:02 +0000, Rodrigo Rebello wrote:

> Besides adding the mentioned field, the included patch also modifies configure.in so that EXTRA_LDFLAGS (which is now also used as the value of 'Libs.private') no longer includes SDL_LIBS. This is done so as to prevent libraries required by SDL from being listed twice when 'pkg-config --libs --static SDL_mixer' is run (they're already shown because of the 'Requires: sdl' line in SDL_mixer.pc). Makefile.in is also adjusted accordingly.

**Comment by sezero** [comment]
This should be fixed by https://github.com/libsdl-org/SDL_mixer/pull/365 (and by https://github.com/libsdl-org/SDL_mixer/pull/366 for the SDL-1.2 branch.)
