### ISSUE TITLE
MinGW: help ./configure find shared libraries for dynamic loading

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL_mixer#238]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [MinGW: help ./configure find shared libraries for dynamic loading (SDL2_mixer-2.0.1-find_lib.mingw.patch, text/plain, 2017-11-10 12:33:20 +0000, 4390 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=3078)

**Reported in version:** 2.0.2
**Reported for operating system, platform:** Linux, x86_64

# Comments on the original bug report:

On 2017-11-10 12:33:20 +0000, Fabian Greffrath wrote:

> Created attachment 3078
> MinGW: help ./configure find shared libraries for dynamic loading
> 
> We apply the attached patch to the mingw-w64-SDL2_mixer package in MSYS2:
> 
> https://github.com/Alexpux/MINGW-packages/tree/master/mingw-w64-SDL2_mixer
> 
> When using the 64-bit variant of the MinGW compiler, the configure script fails to find any of the installed shared libraries for dynamic linking. The patch fixes this issue by replacing the "*-*-mingw32*" search pattern with "*-*-mingw*".
> 
> Then, some libraries are installed with a "lib" prefix while others are not. I have extended the problematic cases with both alternatives.
> 
> Last but not least, libraries might have been installed into any of the directories accessible via the PATH environment variable, so we search in these paths as well.
> 
> Best regards,
> 
>  - Fabian

**Comment by sezero** [comment]
@icculus, @slouken: I intend to replace all host checks of the like `mingw32*` with `mingw*`
in _all_ of the SDL projects,. Any objections?

**Comment by sezero** [comment]
> @icculus, @slouken: I intend to replace all host checks of the like `mingw32*` with `mingw*`
> in _all_ of the SDL projects,. Any objections?

Replaced all host checks of the like mingw32* with mingw* in all of the SDL projects.
Looking at the rest of the issues now.

**Comment by sezero** [comment]
Applied improve fluidsynth and tremor dll detection for windows

**Comment by sezero** [comment]
Re: PATH environment:
I don't think it would be a good idea adding this to `find_lib`.  @slouken?
Can we close this?

**Comment by sezero** [comment]
Closing.
