### ISSUE TITLE
MinGW: compile version.rc into a libtool object

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL_mixer#239]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [MinGW: compile version.rc into a libtool object (SDL2_mixer-2.0.1-libtool_windres.mingw.patch, text/plain, 2017-11-10 12:37:03 +0000, 1069 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=3079)

**Reported in version:** 2.0.2
**Reported for operating system, platform:** Linux, x86_64

# Comments on the original bug report:

On 2017-11-10 12:37:03 +0000, Fabian Greffrath wrote:

> Created attachment 3079
> MinGW: compile version.rc into a libtool object
> 
> We apply the attached patch to the mingw-w64-SDL2_mixer package in MSYS2:
> 
> https://github.com/Alexpux/MINGW-packages/tree/master/mingw-w64-SDL2_mixer
> 
> It compiles version.rc into a libtool object, which somehow suddenly becomes necessary after running autoreconf over the sources (which we do after applying the patch in # 3952).
> 
> Best regards,
> 
>  - Fabian

**Comment by sezero** [comment]
Applied a modified form of the patch as 3e2dea6ecf90aa3
