### ISSUE TITLE
Issue reusing a Mix_Music more than once

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL_mixer#245]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [minimal example to reproduce the issue (file_4138.txt, text/plain, 2018-04-16 06:57:19 +0000, 1221 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=3223)

**Reported in version:** unspecified
**Reported for operating system, platform:** Linux, x86_64

# Comments on the original bug report:

On 2018-04-16 06:57:19 +0000, Michele Caini wrote:

> Created attachment 3223
> minimal example to reproduce the issue
> 
> Consider the following:
> 
>     Mix_Music *m1 = Mix_LoadMUS("foo.mp3");
>     Mix_Music *m2 = Mix_LoadMUS("foo.mp2");
> 
>     Mix_PlayMusic(m1, -1);
>     // do things for N seconds
>     Mix_PlayMusic(m2, -1);
>     // do things for M seconds
>     Mix_PlayMusic(m1, -1);
> 
> Note that I don't free neither m1 nor m2 in any case.
> 
> Here the problem: when I play m1 the second time, a few ms of the music from the point where it was when I stopped it the first time are played. Then it resets to the start and plays the whole music from there as expected.
> It looks like a Mix_Music has a buffer it starts playing before doing any other thing.
> 
> Here is a Q/A on SO, actually only a Q so far - https://stackoverflow.com/questions/49836263/issue-reusing-a-mix-music-more-than-once
> From the question above, you can get this link where you can find a short snippet to reproduce the issue (many thanks to the author) - https://gist.github.com/araml/7191ba537e497cc1ccd7e0199c65bdc6
> I'm creating also an attachment with exactly the same code.
> 
> It happens with all the mp3 files I tried so far, so I don't think it depends on the file itself.
> If you want a file that I used to reproduce the issue, here it is - https://ozzed.net/music/8-bit-empire.shtml#tune01

**Comment by RustyMoyher** [comment]
I'm also experiencing the same issue, but I'm using WAV files. I believe the issue first appeared in SDL_Mixer 2.0.2. I can still reproduce it in SDL_Mixer 2.0.4.

I've previously only seen the issue on Windows, but today I'm seeing it on Mac too. I think it's now showing in Mac because I've started transitioning all my audio from 44100 khz -> 48000 khz + calling Mix_OpenAudio() w/ 48000.

My current workaround is to use SDL_Mixer 2.0.1 when possible.

version: SDL_Mixer 2.0.4, SDL 2.0.14
platform: Windows 10, x86_64

**Comment by RustyMoyher** [comment]
I have a workaround now. Calling SDL_AudioStreamClear() on the current stream before Mix_PlayMusic() clears the unplayed buffer in the Mix_Music.

However, the current way I’m accessing the Mix_Music stream is _very_ hacky. Is it possible to call SDL_AudioStreamClear() on Mix_Music somehow using the public API?

**Comment by slouken** [comment]
Yep, this is implemented in https://github.com/libsdl-org/SDL_mixer/commit/fbf6f67729bc892e297e136cd18a226cbf656fe4.
