### ISSUE TITLE
ModPlug playing old dos .AMF format

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL_mixer#255]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [From CF2 Soundtrack (03 - Heli Animation.amf, application/octet-stream, 2018-12-15 23:27:08 +0000, 37953 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=3549)

**Reported in version:** 2.0.4
**Reported for operating system, platform:** Windows 10, x86_64

# Comments on the original bug report:

On 2018-12-15 23:27:08 +0000,  wrote:

> Created attachment 3549
> From CF2 Soundtrack
> 
> Related to this topic: 
> https://discourse.libsdl.org/t/back-to-integrate-mikmod-into-sdl2-mixer/25465/2
> 
> Some Cannon Fodder 2 soundtrack .AMF musics aren't played good by lib ModPlug.
> 
> File "02 - Menu.amf": you can heard some "biiip" whistle near at 38sec and 40sec
> File "03 - Heli Animation.amf": same "biip" at the very start of song
> 
> I known ModPlug is a plugin/codec for modern Players (like VLC, Winamp, etc), but could it be fixed to play AMF correctly, like MikMod lib does, or even old dos Dual Module Player does?
> 
> Otherwise put back again LibMikMod on SDL2_mixer and use it for AMF format.

On 2018-12-16 07:17:21 +0000, Ozkan Sezer wrote:

> (In reply to drnovice from comment # 0)
> > I known ModPlug is a plugin/codec for modern Players (like VLC, Winamp,
> > etc),
> 
> It may be, but it has been always full of serious bugs, some of which
> has only recently fixed.
> 
> >  but could it be fixed to play AMF correctly, like MikMod lib does, or
> > even old dos Dual Module Player does?
> > 
> > Otherwise put back again LibMikMod on SDL2_mixer and use it for AMF format.
> 
> This should be reported at https://github.com/Konstanty/libmodplug
> but let's keep this open too:  Maybe I can find some time and find
> the source of the issue.

On 2018-12-16 13:47:41 +0000,  wrote:

> Yes, LibMikMod is release version 3.3.11.1, series 3:
> http://mikmod.sourceforge.net/
> 
> I think it could be possibile maintain both MikMod & ModPlug, compiling dynamic or static linking to SDL2_Mixer, and give a priority to play same managed audio formats in case both libs are present.
> 
> I can PR on github an update of sln and visual studio project to using latest versions of them.

On 2021-02-07 18:15:09 +0000, Ozkan Sezer wrote:

> FWIW, I tried running current SDL_mixer development tree with the
> attached amf file here, I cannot hear that 'beep' when playing it
> with the playmus example app.
> 
> Do you still experience your issue with current development source?

**Comment by sezero** [comment]
No answer from the OP. Closing as 'worksforme'
