### ISSUE TITLE
SDL mixer does not load in Windows 10 x64

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL_mixer#256]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.4
**Reported for operating system, platform:** Windows 10, x86_64

# Comments on the original bug report:

On 2018-12-31 02:02:16 +0000, Lísias de Castro wrote:

> Hi guys. I am working on an engine with SDL for years.
> I used to compile it in x86 version. But I've downloaded
> MinGWx64 and decided to compile to x64 indead. The compilation
> seems to do well at first moment. But when I try to execute
> the code, no sound is coming out. Without change a single line
> I change to the x86 version and it works well.
> 
> This is the github link for the starting file:
> 
> https://github.com/saisilcastro/Place/blob/master/Place-Shared/sdl_plugin.c

**Comment by sezero** [comment]
Possibly an accidental mix of x86 and x64 dlls. Closing.
