### ISSUE TITLE
two potential bugs in effect_position.c file

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL_mixer#261]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.4
**Reported for operating system, platform:** Windows 7, x86

# Comments on the original bug report:

On 2019-05-31 15:31:31 +0000, AltairPL wrote:

> 1. all loops in _Eff_position_u8_c4() look like this:
> ```c
>    for (i = 0; i < len; i += sizeof (Uint8) * 6)
> ```
> Shouldn't multiplier be 4 here (as in other _c4 functions)?
> 
> 2. IMHO, angle adjustment in Mix_SetPosition() is incorrect, since passing -90 angle will simply change it to 90 instead of 270. I think it should be something like:
> ```c
>     angle %= 360;
>     if (angle < 0) angle += 360;
> ```

**Comment by sezero** [comment]
@icculus, @slouken: I tend to agree with the issue reporter. Comments?

**Comment by icculus** [comment]
> Shouldn't multiplier be 4 here (as in other _c4 functions)?

I haven't looked at this code in a _long_ time, but that definitely looks like a copy/paste bug to me.

**Comment by sezero** [comment]
Copy/paste bug fixed by commit e7cb61327f in 2.0 and commit c99c29a05b
in 1.2 tree.

**Comment by sezero** [comment]
Should we change the angle adjustment in `Mix_SetPosition` as suggested by the issue reporter?

**Comment by slouken** [comment]
Yes, the suggested angle adjustment also seems correct.

**Comment by sezero** [comment]
Angle adjustment fixed by commit 502f4e217dc in 2.0 and commit 81b88d9b6 in 1.2 tree.

Closing.
