### ISSUE TITLE
end of mp3 is cut off depending on chunksize

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL_mixer#281]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [sdl.py (sdl.py, text/x-python, 2020-02-07 00:18:56 +0000, 1312 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=4194)
* [the mp3 file (sdl.mp3, application/octet-stream, 2020-02-07 00:19:41 +0000, 14061 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=4195)

**Reported in version:** 2.0.4
**Reported for operating system, platform:** Linux, x86_64

# Comments on the original bug report:

On 2020-02-07 00:18:56 +0000, Sven wrote:

> Created attachment 4194
> sdl.py
> 
> So find attached a very simple test program (python, PySDL2 0.9.6) that loads and plays an mp3. The mp3 is the sound of somebody saying "Please play this message". If the chunksize passed to Mix_OpenAudio is 8192, the problem is most severe. The end of the word "message" is cut off. If I change the chunksize to 4096, the problem is less severe. In both cases, I assume that the last chunk of the mp3 is not played. The larger the chunksize, the more of the mp3 is not played.
> 
> This should not happen, regardless of the chunksize.
> 
> If I change the chunksize to 4000, I can work around the problem. I assume, there might be mp3 files for which the problem will persists.
> 
> Sorry that the program is python. I'm on Arch Linux using sdl2_mixer 2.0.4-3 and python-pysdl2 0.9.6-4 from Arch's AUR. As far as I can see, python is a rather thin layer on top the C API. So I assume the bug persists if I would rewrite the program in C.

On 2020-02-07 00:19:41 +0000, Sven wrote:

> Created attachment 4195
> the mp3 file

**Comment by a-hurst** [comment]
@sezero As the current maintainer of PySDL2 I figured I'd try and reproduce this. Sure enough, "message" becomes "messa-" with 8192 chunksize, and `Mix_Playing(-1)` seems to think the audio's done even sooner, with the last playthrough of the clip being "please play this-".

The original bug reporter is correct that PySDL2 is just direct ctypes bindings around the SDL2 API, so I'm assuming this isn't a bug on my end. Also, for what it's worth, I reproduced the bug on macOS 10.14 using the official libSDL frameworks, so we can rule it out being a Linux-specific issue.

**Comment by sezero** [comment]
If SDL_mixer is using its mpg123 backend, the issue is reproducible with `playmus -l -b 8192 sdl.mp3`
The libmad backend seems fine (--disable-music-mp3-mpg123 --enable-music-mp3-mad-gpl)

**Comment by sezero** [comment]
The SDL-1.2 branch doesn't seem to have the issue.

**Comment by sezero** [comment]
Looking at the same thing for hours, I don't exactly see where the issue is.
@slouken?

**Comment by sezero** [comment]
These doesn't explain why things are OK if SDL_mixer is using libmad instead of mpg123 for mp3 (can you confirm that?), or am I missing something? It's late here though, and I'm tired.

**Comment by a-hurst** [comment]
> These doesn't explain why things are OK if SDL_mixer is using libmad instead of mpg123 for mp3 (can you confirm that?), or am I missing something?

If I have time today I can try recompiling with libmad, but my thought is that maybe the mpg123 backend is mis-reporting the size of the chunk (or maybe libmad is over-reporting it, which fixes the issue)? Either way, the values of those variables should at least point in the right direction. Also, given that it worked with the SDL-1.2 branch (linking to SDL1.2 and not SDL2, I'm assuming?), it could be related to some subtle change in how SDL2 itself handles chunk sizes.

What I *can* do pretty quickly is check whether the bug is present on a really old version of SDL2 + Mixer (PySDL2 supports back to SDL2 2.0.5 and mixer 2.0.1) to see how far the bug goes. That'll also hopefully help pinpoint where to look.

**Comment by a-hurst** [comment]
@sezero Aha! The test script plays the mp3 all the way through at 8192 with SDL 2.0.5 and mixer 2.0.1, 2.0.6 + 2.0.1 fails to play the audio at all with a `Warning: incorrect audio format` message, and 2.0.7 + mixer 2.0.2 show the same cutoff bug we see in the latest versions. That at least tells us where to look!

My hunch from the error with 2.0.6 is that SDL2 changed something on the audio back end that broke mixer, and the fix added in 2.0.2 addressed the main issue but also introduced the bug we're seeing here.

**Comment by sezero** [comment]
With current git master where drmp3 is default, the issue doesn't show itself.

HOWEVER: build SDL_mixer with `--enable-music-mp3-mpg123 --disable-music-mp3-drmp3`
and the issue is still reproducible.
