### ISSUE TITLE
SDL2_mixer embedded frameworks fail code signature and notarization checks

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL_mixer#286]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.4
**Reported for operating system, platform:** macOS 10.15, x86_64

# Comments on the original bug report:

On 2020-06-20 15:25:08 +0000, ioanch wrote:

> The following frameworks embedded in SDL2_mixer.framework are "not signed at all" and require me to put something like "codesign -f -s - <framework>" to allow bundling into an .app (my bundle contains a separate executable as a resource, and THAT executable links to those frameworks):
> 
> FLAC Ogg Opus OpusFile Vorbis modplug mpg123
> 
> The following frameworks have incorrect Info.plist files. They're missing the mandatory `<key>CFBundleSupportedPlatforms</key><array><string>MacOSX</string></array>` string:
> 
> FLAC Opus OpusFile modplug mpg123

On 2020-06-24 20:32:53 +0000, Ozkan Sezer wrote:

> The mandatory CFBundleSupportedPlatforms key issue is already
> fixed in the hg repository:
> https://hg.libsdl.org/SDL_mixer/rev/58707cd78f95

**Comment by sezero** [comment]
The missing required key has been added for some time. Closing.
