### ISSUE TITLE
SDL_mixer on MacOS: Silicon / ARM support

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL_mixer#291]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.4
**Reported for operating system, platform:** Mac OS X (All), ARM

# Comments on the original bug report:

On 2021-01-18 08:46:19 +0000,  wrote:

> Not a bug per se, but the MacOS .dmg for SDL_mixer 2.0.4 doesn't include support for Apple Silicon. Quite logical since the last release was in 2018.
> 
> Could you perhaps update the .dmg to include arm, so all projects that depend on it don't have to recompile the framework themselves when they want to support Apple Silicon macs natively?

**Comment by pingwinator** [comment]
any news?

**Comment by Cacodemon345** [comment]
I don't think this will be fixed until the next release.

**Comment by bvschaik** [comment]
Question related to this: for the Xcode build, the mpg123, vorbis, etc libraries are provided as pre-compiled frameworks. How do I update/recompile those?
Compiling for arm64 seems to work but it cannot link the frameworks because those do not support arm64.

**Comment by pingwinator** [comment]
the framework doesn't have support for some music libs.

**Comment by ellipticaldoor** [comment]
so just compiling sdl_mixer will not work?

**Comment by ellipticaldoor** [comment]
The compiled version for homebrew works on arm64 so there should not be anything stopping a new release

**Comment by ellipticaldoor** [comment]
someone knows how to build the framework locally for a universal release?

**Comment by sezero** [comment]
Latest git version has added arm64 builds to all music decoder frameworks.
Please test.

**Comment by sezero** [comment]
No response since 1.5 months - Closing as fixed
