### ISSUE TITLE
How to play MP3 on ios?

### ISSUE THREAD

**Issue by cx421774557** [libsdl-org/SDL_mixer#302]
How to play MP3 on ios, try to compile libmpg123, but it fails, is there a solution?

**Comment by Wohlstand** [comment]
Try the recent version with the minimp3, should be much easier. The libMPG123 is tricky to build on some platforms due to assembly fragments.

**Comment by slouken** [comment]
The latest code has support for playing MP3 on iOS and doesn't require libmpg123.

Cheers,
