### ISSUE TITLE
SDL_mixer1.2 - Any planned future release?

### ISSUE THREAD

**Issue by andrew-mcmahon** [libsdl-org/SDL_mixer#315]
Hello SDL devs :smiley: 
  
The question is in the title really but I'll elaborate...  
I've just built [openxcom](https://github.com/OpenXcom/OpenXcom) from source on Debian Testing. _(I don't know if their sdl2 branch is finished yet)_
I've got the game playing MIDI files through fluidsynth with the Fatboy soundfont [#1](https://fatboy.site/) [#2](https://www.youtube.com/channel/UCz8opYYsl2HJbP-OkdhNMcw) i.e:
```
echo $SDL_SOUNDFONTS 
/usr/share/soundfonts/FatBoy-v0.790.sf2
```  
The only issue is - the game segfaults on exit; but your [changelog](https://github.com/libsdl-org/SDL_mixer/blob/SDL-1.2/CHANGES) shows that's a fixed issue in 1.2.13!
```
- Midi (fluidsyth): respect synth.sample-rate limits (bug #3969)
- Midi (fluidsyth): fixed loading MIDI music leaks memory (bug #3018)
- Midi (fluidsyth): fixed calling Mix_Quit twice leading to segfault
  (bug #2004)
```
[openxcom_crash_libsdl-mixer1.2.12.log](https://github.com/libsdl-org/SDL_mixer/files/6335606/openxcom_crash_libsdl-mixer1.2.12.log)
[openxcom_gdb.log](https://github.com/libsdl-org/SDL_mixer/files/6335607/openxcom_gdb.log)
  
If I build the game against the latest and greatest [libsdl_mixer1.2](https://github.com/libsdl-org/SDL_mixer/commit/cc68194f3e1e32b91ae0e18db3375ceebbb34e1f) - I confirm the issue is indeed fixed! :+1: 
[ldd_openxcom.txt](https://github.com/libsdl-org/SDL_mixer/files/6335656/ldd_openxcom.txt)

It would be nice to see this update trickle down through the usual channels.  
Has it really been 9 years since the last 1.x release? That even makes me feel old :older_adult:  
  
Many thanks!

**Comment by sezero** [comment]
As far as I know, the maintainers have no plans to make any releases from
the SDL-1.2 branches, but let's ask: @slouken, @icculus?

**Comment by icculus** [comment]
I don't think we'll be doing any future 1.2 releases; Debian can feel free to cherry-pick fixes for their sdl_mixer1.2 package, though!
