### ISSUE TITLE
Errors have \r\n

### ISSUE THREAD

**Issue by AntTheAlchemist** [libsdl-org/SDL_mixer#320]
I've found at least one error with a carriage return and new line escape codes on the end, which I don't think should be there. Here's one example:

"Failed loading libmodplug-1.dll: The specified module could not be found.\r\n"

There may be more.

**Comment by sezero** [comment]
That particular error message seems to come from SDL_LoadObject(), going through
`src/loadso/windows/SDL_sysloadso.c` -> `src/core/windows/SDL_windows.c`:`WIN_SetError()`
I _guess_ (but not sure) that `FormatMessage()` is adding those `\r\n`.

**Comment by sezero** [comment]
Well, `FormatMessage` seems to be the culprit: https://github.com/libsdl-org/SDL/blob/main/src/hidapi/windows/hid.c#L253

Something like the followin should be applied to https://github.com/libsdl-org/SDL/blob/main/src/core/windows/SDL_windows.c#L43
@slouken, @icculus: OK to push?
```diff
diff --git a/src/core/windows/SDL_windows.c b/src/core/windows/SDL_windows.c
index 22dadd2..e111ec9 100644
--- a/src/core/windows/SDL_windows.c
+++ b/src/core/windows/SDL_windows.c
@@ -44,8 +44,17 @@ WIN_SetErrorFromHRESULT(const char *prefix, HRESULT hr)
 {
     TCHAR buffer[1024];
     char *message;
+    TCHAR *p = buffer;
     FormatMessage(FORMAT_MESSAGE_FROM_SYSTEM, NULL, hr, 0,
                   buffer, SDL_arraysize(buffer), NULL);
+    /* kill CR/LF that FormatMessage() sticks at the end */
+    while (*p) {
+        if (*p == '\r') {
+            *p = 0;
+            break;
+        }
+        ++p;
+    }
     message = WIN_StringToUTF8(buffer);
     SDL_SetError("%s%s%s", prefix ? prefix : "", prefix ? ": " : "", message);
     SDL_free(message);
```

**Comment by slouken** [comment]
Yep, go ahead and push.
