### ISSUE TITLE
"Mix_HasMusicDecoder" defined in header but not implemented in library

### ISSUE THREAD

**Issue by a-hurst** [libsdl-org/SDL_mixer#322]
In the header there's a function named `Mix_HasMusicDecoder`, which is presumably a Music equivalent of `Mix_HasChunkDecoder`: https://github.com/libsdl-org/SDL_mixer/blob/4395f008ce56126b35d42c71f06d814c7173c639/include/SDL_mixer.h#L209

However, there's no corresponding function in `music.c`, so it can't be used! This tripped me up when working with Python bindings for SDL2 (it was trying to import the function from the dylib and failing), thought you might like a heads-up.

**Comment by sezero** [comment]
@slouken: This was your addition but was not implemented. Should we remove it?

**Comment by sezero** [comment]
> From the looks of it, implementing the function should be as easy as copy/pasting the Mix_HasChunkDecoder function and replacing "chunk" with "music" since both systems seem to use the same decoder indexing method:
> 
> ```c
> SDL_bool Mix_HasMusicDecoder(const char *name)
> {
>     int index;
>     for (index = 0; index < num_decoders; ++index) {
>         if (SDL_strcasecmp(name, music_decoders[index]) == 0) {
>             return SDL_TRUE;
>         }
>     }
>     return SDL_FALSE;
> }
> ```
> 
> I haven't tested the code at all, but at a glace it looks like all that would be needed.

@slouken: Use this code (if it is correct)? Or remove the prototype?

**Comment by sezero** [comment]
I went ahead and added the missing procedure as of https://github.com/libsdl-org/SDL_mixer/commit/8d3c364c7d4cbef2c8e004fad703d841d3272a1c
Thanks.
