### ISSUE TITLE
Document library dependencies

### ISSUE THREAD

**Issue by hottwaj** [libsdl-org/SDL_mixer#323]
Hi there, first of all thanks for the awesome set of libraries

For ubuntu/debian devs like me, it would be helpful if there were some installation notes that listed required/optional dependencies that can be e.g. installed via apt?

I think the list of optional dependencies is something like:
- libmodplug-dev, libfluidsynth-dev, libvorbis-dev, libflac-dev, libmpg123-dev, libopus-dev

So the following will do the trick on debian based systems:

```bash
sudo apt install libmodplug-dev libfluidsynth-dev libvorbis-dev libflac-dev libmpg123-dev libopus-dev
```

Thanks!

**Comment by sezero** [comment]
s/libopus-dev/libopusfile-dev/

**Comment by slouken** [comment]
You can use `apt-get build-dep` to install the dependencies of any package. SDL_mixer is available on Ubuntu/Debian, with a full set of specified dependencies.

**Comment by Croydon** [comment]
I still think that this issue needs a proper solution.

Upstream should always document their dependencies in an easily discoverable and readable way. Pointing to one downstream package manager as a solution is kinda weird.
