### ISSUE TITLE
Can't get SDL_mixer to build with OGG support

### ISSUE THREAD

**Issue by Ratstail91** [libsdl-org/SDL_mixer#325]
I've tried everything for days - and nothing seems to work. I finally have libvorbis installed, but the configure script can't find the vorbisfile.h

Help?

**Comment by sezero** [comment]
If you are on debian, or ubuntu or its alikes, you install libvorbis-dev.
If you are on fedora, rhel, centos or its alikes, install libvorbis-devel.

**Comment by Ratstail91** [comment]
I'm on windows using cygwin.

I think it's working, after going in and messing with the make files... but now there's  libpng error.

Strangely, I also have to add this above main:

```cpp
#ifdef main
#undef main
#endif
```

**Comment by sezero** [comment]
lnstall libvorbis-devel (and its dependents) for cygwin. And libpng-devel for png
(I guess you are trying to built SDL_image too.)

As for `main`, I think your exe needs to link with -lSDLmain

**Comment by Ratstail91** [comment]
Sorry, I was stressed out earlier - I finally got it working and building and running correctly in both windows & cygwin, somehow.
