### ISSUE TITLE
Documentation:  link to tutorial has been dead for years

### ISSUE THREAD

**Issue by gbgames** [libsdl-org/SDL_mixer#327]
The SDL_mixer docs (https://www.libsdl.org/projects/SDL_mixer/docs/index.html) mention a link to Roger Ostrander's SDL_Mixer Tutorial at http://www.kekkai.org/roger/sdl/mixer/

But that link gives a 404, and the Internet Archive shows that around 2015 the web host was taken down. 

I did find that his tutorials are at http://www.llynmir.net/~roger/sdl/mixer/index.html

But it looks like they were last updated in 2001, and so they might not be as relevant or updated as desired. 

Still, it looks like if the link should remain, the link needs to be updated.

**Comment by slouken** [comment]
The tutorials have been removed.
