### ISSUE TITLE
MSVC Build Failed For Enconding Problem (From VCPKG)

### ISSUE THREAD

**Issue by Sodacooky** [libsdl-org/SDL_mixer#339]
**Updated from vcpkg days ago and found it couldn't be built through MSVC toolchain in vcpkg.**
In the error log, I got:
```
load_aiff.c(1): warning C4828: The file contains a character starting at offset 0x4dd that is illegal in the current source character set (codepage 65001).
load_aiff.h(1): warning C4828: The file contains a character starting at offset 0x4e7 that is illegal in the current source character set (codepage 65001).
load_aiff.h(1): warning C4828: The file contains a character starting at offset 0x4e7 that is illegal in the current source character set (codepage 65001).
```
Then I noticed load_aiff.h/.c are in **windows 1252** encoding.
If you search in this repo you would find many ".rc" files with content "#pragma code_page(1252)". (but those files are old and some contents show you have tried to convert encoding?

---

That could not be system problem, everything is OK before I updated it.
It might not affect English system but do affect who in other language like me in Chinese.
Have tried to enable/disable Windows's global UTF-8 setting.

---

Windows Home 21H1 (22000.348) Chinese
Visual Studio Build Tool 2019 (16.11.7)
Latest VCPKG

**Comment by slouken** [comment]
Fixed, thanks!
