### ISSUE TITLE
Does SDL_mixer support sound card with multiple output ?

### ISSUE THREAD

**Issue by funcode2** [libsdl-org/SDL_mixer#359]
I tried to send different sound playback on different audio output. It works well on stereo by using set_volume(left, right). (To be precise, here is the code in python. pygame.mixer.Channel(0).set_volume(1.0, 0.0) ). 

I wonder if there is support for 5.1 / 7.1 or just simply support 4 speakers. (Front L/R, Rear L/R). Thanks!

**Comment by slouken** [comment]
Yes, it should work. Please report any issues you run into as separate bugs.
