### ISSUE TITLE
Android NDK build: libmodplug fails to compile with C++17

### ISSUE THREAD

**Issue by SpectralCascade** [libsdl-org/SDL_mixer#360]
When building a C++17 Android studio project with SDL_mixer, the libmodplug dependency causes the NDK build to fail with the following error:

`C:\AndroidLib\SDL2_mixer-2.0.4\external\libmodplug-0.8.9.0\src\fastmix.cpp:678:2: error: ISO C++17 does not allow 'register' storage class specifier [-Wregister]`

It all builds with C++14 but shows some warnings. It seems like libmodplug is rather outdated, having [not been updated since 2020](https://github.com/Konstanty/libmodplug/commits/master). A workaround for C++17 is to disable support in Android.mk, then delete the libmodplug directory and music_modplug.c

**Comment by sezero** [comment]
I had thoroguhly patched the SDL_mixer-contained libmodplug multiple times
which includes the following change:
https://github.com/libsdl-org/SDL_mixer/blob/master/external/libmodplug-0.8.9.0/src/fastmix.cpp#L290

Is it still failing, or are you building SDL_mixer from a release tarball (e.g. 2.0.4)
and not from git?

**Comment by SpectralCascade** [comment]
Ah apologies, this specific issue does indeed seem to be fixed on git; should be good to close, though I note there seems to be a separate issue that also prevents building currently (on commit 2d1d969292861558ad3baba15a6ef869d875ec5b):

`make: *** No rule to make target 'C:\Users\2013b\Git\plumbing_disaster\Android\app\jni\SDL2_mixer\external\mpg123-1.25.6\src\libmpg123\parse.c', needed by 'C:\Users\2013b\Git\plumbing_disaster\Android\app\build\intermediates\cxx\Debug\1w2q3t3x/obj/local/armeabi-v7a/objs-debug/mpg123/src/libmpg123/parse.o'.  Stop.`

**Comment by sezero** [comment]
> Ah apologies, this specific issue does indeed seem to be fixed on git;

OK then, closing.

> should be good to close, though I note there seems to be a separate issue that also prevents building currently (on commit [2d1d969](https://github.com/libsdl-org/SDL_mixer/commit/2d1d969292861558ad3baba15a6ef869d875ec5b)):
> 
> `make: *** No rule to make target 'C:\Users\2013b\Git\plumbing_disaster\Android\app\jni\SDL2_mixer\external\mpg123-1.25.6\src\libmpg123\parse.c', needed by 'C:\Users\2013b\Git\plumbing_disaster\Android\app\build\intermediates\cxx\Debug\1w2q3t3x/obj/local/armeabi-v7a/objs-debug/mpg123/src/libmpg123/parse.o'. Stop.`

I'm not sure what you are doing, but the included mpg123 version in gi is not `1.25.6`, it is `1.25.13`. The top-level Android.mk in SDL_mixer git has it right, so please update your own Android.mk versions for it.
