### ISSUE TITLE
Dangling function prototype: Mix_HasMusicDecoder

### ISSUE THREAD

**Issue by braewoods** [libsdl-org/SDL_mixer#371]
I discovered that SDL_mixer.h has a dangling function prototype for Mix_HasMusicDecoder meaning this does not exist anywhere else in the source code. Was it removed and just forgotten about in the header?

**Comment by sezero** [comment]
See https://github.com/libsdl-org/SDL_mixer/issues/322: the function has been added to git master as of https://github.com/libsdl-org/SDL_mixer/commit/8d3c364c7d4cbef2c8e004fad703d841d3272a1c
