### ISSUE TITLE
suggest  Mix_MusicInterface add type check

### ISSUE THREAD

**Issue by baidwwy** [libsdl-org/SDL_mixer#372]
https://github.com/libsdl-org/SDL_mixer/blob/6845d9f3cb3f35542f1ec7e74dba6b30bf968959/src/mixer.c#L550

for example
~~music_type = detect_music_type(src);~~
interface->Checktype(src);

https://github.com/libsdl-org/SDL_mixer/issues/332

**Comment by baidwwy** [comment]
https://github.com/libsdl-org/SDL_mixer/blob/6845d9f3cb3f35542f1ec7e74dba6b30bf968959/src/mixer.c#L554

I want to add sndfile, but this check is blocking me

**Comment by slouken** [comment]
I think we want to just add the correct detection code to detect_music_type(), no?

**Comment by baidwwy** [comment]
https://github.com/libsdl-org/SDL_mixer/pull/499
