### ISSUE TITLE
Main branch is named "master"

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL_mixer#373]
Heads up, I'm going to rename the "master" branch to "main" to match all the other SDL repositories; this was an oversight that I missed this in SDL_mixer when importing everything.

There will be instructions on how to move your local copy to the new name, that will pop up on https://github.com/libsdl-org/SDL_mixer/ the first time you go there after I change this, but if you have any meaningful commits pending, you should commit and push now, because it's always easier to just delete your local copy and reclone it.   :)

I'll be doing this within the next 24 hours; plan accordingly!

**Comment by icculus** [comment]
(also, fwiw, this is not a traumatic change to make; we aren't rebuilding the repository or anything, it's more like updating a bookmark...there's UI in GitHub to handle it.)

**Comment by icculus** [comment]
Okay, this is done. In case you accidentally clicked through the "here's how to change your local copy" instructions, this will move your copy from "master" to "main" ...

```bash
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```

...and then just carry on like you did before.

**Comment by CrezyDud** [comment]
w h y

**Comment by icculus** [comment]
Because every other repo was using "main."
