### ISSUE TITLE
wavpack support?

### ISSUE THREAD

**Issue by sezero** [libsdl-org/SDL_mixer#382]
Do we want wavpack support?

https://en.wikipedia.org/wiki/WavPack
https://www.wavpack.com/
https://github.com/dbry/WavPack

**Comment by slouken** [comment]
Possibly, do we have anyone asking for it?

**Comment by sezero** [comment]
No - was just asking because it's a pretty common format

**Comment by slouken** [comment]
Okay, I threw it on the 2.8.0 milestone.
