### ISSUE TITLE
change stb_vorbis.h to use 64 bit sample numbers and offsets?

### ISSUE THREAD

**Issue by sezero** [libsdl-org/SDL_mixer#396]
Opening this ticket here so it doesn't get lost. The original discussion
was at https://github.com/libsdl-org/SDL_mixer/pull/395#issuecomment-1133705993

The short version is: @Wohlstand says that plain 32bit signed integer is
able to address ~3 hours of 198000 kHz audio. Longer than that is trouble
and needs int64 sample number / offset.

He reported the issue to mainstream at https://github.com/nothings/stb/issues/1329

The affected apis / structure members seem to be the following:

- `stb_vorbis_get_sample_offset`, and `stb_vorbis_get_playback_sample_offset`
  from mainstream PR/1295:  they return `int` instead of int64.

- `stb_vorbis_stream_length_in_samples`: returns `unsigned int`
  instead of int64.

- `stb_vorbis_seek`: takes `unsigned int` as the `sample_number` parameter
  instead of int64.

- `struct stb_vorbis`::`total_samples`: `uint` type instead of int64.

- `struct stb_vorbis`::`current_playback_loc` (from Vitaly's mainstream
  PR/1295): `int32` type instead of int64.
  HOWEVER: @Wohlstand's PR/1295 doesn't change the `current_loc` member
  and keeps it as `uint32`, it _may_ need changing too.

**Comment by sezero** [comment]
And here goes our answer from https://github.com/nothings/stb/issues/1329: `libsdl probably should be using libvorbis, not stb_vorbis`

**Comment by slouken** [comment]
That makes sense. People who need the robustness of libvorbis (e.g. process 5 hours of studio audio) can build SDL_mixer with it, and those who want fast, lean code for games can build SDL_mixer with the default stb_vorbis option. Linux distributions are likely to build SDL_mixer with libvorbis since it's available as part of the platform.

We can discuss this more, but I think we can close this for now.

**Comment by Wohlstand** [comment]
> PR/1295 

That pull request I made doesn't intend to change integer types, it adds only missing functionality. Integer changing is totally different work. That I did at PR/1331 today.
