### ISSUE TITLE
wrong mp3 duration with libmad backend

### ISSUE THREAD

**Issue by sezero** [libsdl-org/SDL_mixer#403]
One mp3 I have reports 56.607347s duration instead of about 31.320816s
with libmad backend: I can attach the mp3 in question here.

_Originally posted in https://github.com/libsdl-org/SDL_mixer/issues/300#issuecomment-1140079544_

**Comment by slouken** [comment]
Yes, please attach the MP3 file.

**Comment by slouken** [comment]
As an aside, why do we have support for libmad?
We have a public domain implementation that's enabled by default, and an LGPL backend as well. Are they not as functional as libmad?

**Comment by sezero** [comment]
> Yes, please attach the MP3 file.

Here goes: [mp3.zip](https://github.com/libsdl-org/SDL_mixer/files/8790032/mp3.zip)

It's a mp3 convert of a game music though, so remember to delete this reply later.

**Comment by sezero** [comment]
> As an aside, why do we have support for libmad? We have a public domain implementation that's enabled by default, and an LGPL backend as well. Are they not as functional as libmad?

Well, it _is_ a good library. But we have two other good backends too, so should we remove it?

**Comment by slouken** [comment]
Yes, let's go ahead and do that.

**Comment by sezero** [comment]
Will push a patch shortly.

What about libmikmod support? We have 3 backends for mod support: libmodplug (which
is a zombie project but public domain), libxmp which is a very good library, and libmikmod
which is LGPL (which some also considers a zombie who should die). Should we remove
libmikmod support too?

**Comment by sezero** [comment]
> Yes, let's go ahead and do that.

Done.

**Comment by Wohlstand** [comment]
libmikmod is the worst one by features support and introduces a lot of limitations like an ability to run only one file at the same time (makes a problem when attempting to load a module as a chunk when playing any module music at the same time, for example).

**Comment by slouken** [comment]
> What about libmikmod support? We have 3 backends for mod support: libmodplug (which is a zombie project but public domain), libxmp which is a very good library, and libmikmod which is LGPL (which some also considers a zombie who should die). Should we remove libmikmod support too?

Sure, I think libmodplug supersedes libmikmod at this point.

**Comment by slouken** [comment]
libmad is no more, closing this bug.

**Comment by sezero** [comment]
> Sure,

OK, will push a patch shortly

> I think libmodplug supersedes libmikmod at this point.

That's debatable in terms of quality. If it were me, I'd made libxmp
as the default mod backend.

**Comment by Wohlstand** [comment]
P.S.: Speaking about MP3 duration (just in general talk, out of any work), there first think that the file has an invalid tag or chunk with the wrong data (or something unusual that wasn't known). That may happen at Frankenshtein streams or basically wrong tag attached to the file, and it got been taken as truth. These broken files may cause problems even at VLC and other players (I have one Frankenshtein file sent me a while ago, and it glitched at VLC against the length).

**Comment by sezero** [comment]
> P.S.: Speaking about MP3 duration [...] Frankenshtein streams

FWIW, the file I tested is not a Frankenstein mp3.

**Comment by sezero** [comment]
Sam: make sure the xcode and msvc project files aren't broken after libmad and libmikmod support removals.

**Comment by slouken** [comment]
> Sam: make sure the xcode and msvc project files aren't broken after libmad and libmikmod support removals.

Yup, looks good.
