### ISSUE TITLE
Android Studio project no longer builds: 

### ISSUE THREAD

**Issue by AntTheAlchemist** [libsdl-org/SDL_mixer#408]
Since the recent changes, I can no longer build my Android project. I get this error "SDL2_mixer depends on undefined modules: modplug".

I'm not sure what to do. It seems the modplug library is missing from the mixer source code? is this because it's changed to a github sub-project, so I have to add it manually now? Where do I save it to, what directory name? Do I need to edit my .mk files to do this? I download the .zip file of the code and save it to a specific directory, I don't use any github software to pull the source code.

**Comment by AntTheAlchemist** [comment]
I downloaded the modplug source and managed to get it to build, but now I get another error in logcat "Couldn't find function SDL_main in library".  

This all worked no problem before the recent changes to mixer.

**Comment by slouken** [comment]
Did you run download.sh in the external directory?

There shouldn't be any relation to SDL_main in SDL_mixer. I'm not sure what's happening there. Do you have a link to your project available?

**Comment by AntTheAlchemist** [comment]
I can't share unfortunately because it's a commercial game. I'm currently dissecting the project and I think I know what's gone wrong and it's probably not SDL's fault. Will update when I've found the problem.

**Comment by AntTheAlchemist** [comment]
Sorted it, it's not SDL - sorry! The sub-project github link for modplug made me chase down a rabbit hole.

**Comment by AntTheAlchemist** [comment]
I did notice something else. Do we no longer need to @Override getLibraries() to add "SDL2_mixer"? Seems to work without it now?

**Comment by slouken** [comment]
> I did notice something else. Do we no longer need to @OverRide getLibraries() to add "SDL2_mixer"? Seems to work without it now?

I think you do need to override getLibraries(). If you're not seeing that, it's worth investigating why that is.
