### ISSUE TITLE
[Question] Do the released Windows binaries support Fluidsynth?

### ISSUE THREAD

**Issue by mikeday0** [libsdl-org/SDL_mixer#413]
Do the released Windows binaries found [here](https://www.libsdl.org/projects/SDL_mixer/) get built with any kind of Fluidsynth support? Doing some quick testing with `Mix_GetMusicDecoder()` suggests that the answer is **no** but it's highly likely I'm doing something wrong. Thanks!

**Comment by slouken** [comment]
No, fluidsynth isn't built by default on any platform.

**Comment by mikeday0** [comment]
Thanks for the confirmation!

**Comment by slouken** [comment]
You're welcome! :)
