### ISSUE TITLE
Vendored libmodplug not installing correctly with CMake

### ISSUE THREAD

**Issue by a-hurst** [libsdl-org/SDL_mixer#420]
I've been switching over the Linux build script for pysdl2-dll (pre-compiled multiplatform binaries for PySDL2) to build image/ttf/mixer using the new-and-improved CMake system, and overall it's much cleaner and nicer than building each library and all its external dependencies manually using autotools. Nicely done!

However, I think I've caught a small bug in the CMakeLists.txt for mixer:

https://github.com/libsdl-org/SDL_mixer/blob/b0fc0348b4be986621841715d8be45aa170b9bc1/CMakeLists.txt#L553-L555

In the part of the script that handles building a vendored version of libmodplug, when deciding whether to install the binary in the target prefix or not, it checks the `SDL2MIXER_FLAC_LIBFLAC_SHARED` variable instead of the `SDL2MIXER_MOD_MODPLUG_SHARED` one, so if you're using `dr_flac` instead of `libflac` libmodplug gets built but never installed.

For now I'm just working around it by patching the CMakeLists.txt in my script before using it.

**Comment by slouken** [comment]
Thanks, can you attach a patch?

**Comment by a-hurst** [comment]
Sure, here you go!

[modplug_fix.patch.txt](https://github.com/libsdl-org/SDL_mixer/files/9078092/modplug_fix.patch.txt)

**Comment by sezero** [comment]
Looks like a simple copy+paste mistake. Patch applied as b60b64fdfd1b210bf5c7c7fa87c79d2f1bd257ea

**Comment by a-hurst** [comment]
Great, thanks so much!
