### ISSUE TITLE
2.5.2/2.6.0 regression: version number in SDL2_mixer.pc is empty

### ISSUE THREAD

**Issue by smcv** [libsdl-org/SDL_mixer#421]
To reproduce: Build SDL_mixer with Autotools, like Debian does. Install it. Run `pkg-config --modversion SDL2_mixer`

Expected result: `2.6.0` or whatever the version is.

Actual result: empty output

This causes dependent packages to fail to build if they have a pkg-config check for `SDL2_mixer >= 2.0.0` or similar.

---

Pull request will follow. I think we should cherry-pick the fix to the `release-2.6.X` branch and do a SDL_mixer 2.6.1 bugfix release, perhaps with a cherry-pick of b60b64f as well.

**Comment by sezero** [comment]
> Build SDL_mixer with Autotools, like Debian does

@smcv: Briefly looked at your debian/rules file, here are a few minor notes:

- `--disable-music-mp3-mad-gpl` is no longer recognized: libmad support
  is removed.

- `--disable-music-mod-mikmod` is no longer recognized: mikmod support
  is removed.  Maybe you want `--disable-music-mod-xmp` instead (Although
  libxmp, especially v4.5.0 and newer should be preferred over libmodplug,
  IMO, but whatever.)
