### ISSUE TITLE
2.6.1 Release Windows VC development x64 lib missing exports

### ISSUE THREAD

**Issue by TheCherno** [libsdl-org/SDL_mixer#425]
After trying to get a project to build I found that `lib/x64/SDL2_mixer.lib` in the `SDL2_mixer-devel-2.6.1-VC.zip` archive for the 2.6.1 release seems to be missing several exports. Doing a `DUMPBIN /EXPORTS` shows 75 symbols compared to 94 for 2.6.0.

Specifically, my issue is that `Mix_PlayChannel` does not exist (only the older `Mix_PlayChannelTimed`), and also `Mix_LoadWAV` does not exist (only the older `Mix_LoadWAV_RW`). Both of these are correctly present in 2.6.0. This of course results in linking errors when trying to use those functions when building with 2.6.1.

**Comment by slouken** [comment]
fixed, thanks!
[SDL2_mixer-devel-2.6.1-VC.zip](https://github.com/libsdl-org/SDL_mixer/releases/download/release-2.6.1/SDL2_mixer-devel-2.6.1-VC.zip)
