### ISSUE TITLE
Outdated README.TXT and update help

### ISSUE THREAD

**Issue by ricardobusta** [libsdl-org/SDL_mixer#430]
After commit `52d3f2c2a870d6b707b95fbfad6c814a66eb485e` my builds started failing because of options changes and/or something else that got changed in the cmake refactor. 

I am using SDL_mixer repo as a submodule of my project and adding the project via cmake. I was previously in commit `1daa96a48204569fcd1a07a768cf2dd92bc596d9`

According to Readme.txt file, I had to do e.g. `option(SUPPORT_OGG "" ON)` to enable stuff, but now they seem to be enabled by default. The options were renamed to `SDL2MIXER_*` instead, which is not reflected in the readme. 
Even replacing those, my builds are still failing with `Could NOT find opusfile (missing: opusfile_LIBRARY opusfile_INCLUDE_PATH)` even if the submodule is checked out and the libraries seems to be there. Not entirely sure how to migrate past that version.

Thanks in advance!

**Comment by madebr** [comment]
On Linux, SDL_mixer is using system libraries by default.
For using the vendored submodules, you need to pass `-DSDL2MIXER_VENDORED=ON`.

**Comment by slouken** [comment]
We have a custom version of opusfile that has some CMake fixes, did you run `external/download.sh` like it says in README.txt?

Here it is in Git, if that helps:
https://github.com/libsdl-org/opusfile/tree/v0.12-SDL

**Comment by ricardobusta** [comment]
> We have a custom version of opusfile that has some CMake fixes, did you run `external/download.sh` like it says in README.txt?
> 
> Here it is in Git, if that helps: https://github.com/libsdl-org/opusfile/tree/v0.12-SDL

Yep, I did not specifically run this script, but I had this working before the CMake changes by doing `submodule update --init --recursive` which seems to do the same thing. The custom version source seems to be there in the correct commit.

I will keep trying to see if I figure out what's missing.

BTW I am trying to build on Windows. Forgot to mention that.

**Comment by ricardobusta** [comment]
> On Linux, SDL_mixer is using system libraries by default. For using the vendored submodules, you need to pass `-DSDL2MIXER_VENDORED=ON`.

Ok, I tried this and it worked! Thank you! :) 
So updating the README file should be enough to clear this up.

**Comment by madebr** [comment]
Only when using the Visual C compiler or targeting Android, the CMake script will use vendored dependencies by default:
https://github.com/libsdl-org/SDL_mixer/blob/bc9c9d7aca93d82eb9f27845a2f72789d6031e71/CMakeLists.txt#L44-L51

If you are using a MingW toolchain, then it will use system libraries by default.
