### ISSUE TITLE
Added looping support for Opus files

### ISSUE THREAD

**Issue by Alice-Thirty** [libsdl-org/SDL_mixer#435]
Added looping support for Opus files
Fixed loading Opus audio as audio chunks

```
CMake Error at /usr/local/Cellar/cmake/3.23.3/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find opusfile (missing: opusfile_LIBRARY opusfile_INCLUDE_PATH)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.23.3/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  cmake/Findopusfile.cmake:18 (find_package_handle_standard_args)
  CMakeLists.txt:374 (find_package)
```

**Comment by slouken** [comment]
Did you run external/download.sh, as it says in README.txt?

**Comment by Alice-Thirty** [comment]
I use   
git clone --recursive https://github.com/libsdl-org/SDL_mixer.git
So my external has the opusfile  folder

Does I need to assign the path to opusfile ?
If do this, how can I do with command

**Comment by slouken** [comment]
@madebr, do you know what's going on here?

**Comment by madebr** [comment]
The error message contains [`FindPackageHandleStandardArgs`](https://cmake.org/cmake/help/latest/module/FindPackageHandleStandardArgs.html), which means the error origins from a find module.
In CMake, find modules are used to find (system) dependencies.

On Linux, the cmake script uses system dependencies by default, which aren't available on your system apparently.
You've got 2 ways to fix this:
1. install the opusfile development package, provided by your package manager (`opusfile-dev'`, `opusfile-devel`, ...   The name depends on your linux distribution)
2. Configure the CMake script to use our vendored libraries. For this, you need to configure CMake with `-DSDL2MIXER_VENDORED=ON`.

**Comment by madebr** [comment]
@Alice-Thirty 
Does [this fix your issue](https://github.com/libsdl-org/SDL_mixer/issues/435#issuecomment-1202553427)?
If not, please comment here and we'll re-open.

**Comment by Alice-Thirty** [comment]
I build on macOS, is it still the  -DSDL2MIXER_VENDORED=ON

**Comment by madebr** [comment]
All options should have the same behavior on all supported platforms. 
It's just the default value that is different.

**Comment by feresr** [comment]
I'm bringing SLD_Mixer into my project like this:
```
FetchContent_Declare(
        SDL2_mixer
        GIT_REPOSITORY https://github.com/libsdl-org/SDL_mixer.git
        GIT_TAG release-2.6.1 # grab latest stable release
        GIT_PROGRESS TRUE
)
FetchContent_MakeAvailable(SDL2 SDL2_mixer)
```

And bumping into this issue

**Comment by madebr** [comment]
https://github.com/libsdl-org/SDL_mixer/issues/435#issuecomment-1202553427 also applies.

You need to set the cmake variable`SDL2MIXER_VENDORED` to a true-ish variable:
- Keep it user configurable and pass it yourself when configuring your project:
    ```sh
    cmake .. -DSDL2MIXER_VENDORED=ON
    ```
- Change the default in your code:
    ```cmake
    set(SDL2MIXER_VENDORED ON CACHE BOOL "")
    FetchContent_Declare(...)
    ```

**Comment by feresr** [comment]
Thank you @madebr! This fixed my issue
