### ISSUE TITLE
Xcode project fails to build Static Library for iOS

### ISSUE THREAD

**Issue by grimaldini** [libsdl-org/SDL_mixer#440]
Repro steps:
1. Git clone repo
2. Open Xcode project in Xcode folder (Xcode 14 beta 6)
3. Select Static Library scheme
4. Select an iOS simulator (I used iPhone SE, 3rd gen and iPhone 8, iOS 16)
5. Build

Result: Failed to compile, SDL headers not found.
Actual error:
effect_position: "'SDL_endian.h' file not found"
native_midi_macos: "'SDL_config.h' file not found"...

**Comment by slouken** [comment]
The SDL framework included in the repo doesn't have iOS simulator binaries. You'll need to build SDL yourself and drop it into the Xcode/iOS directory.
