### ISSUE TITLE
CMake name change: sdl2-mixer-config.cmake to sdl2_mixer-config.cmake

### ISSUE THREAD

**Issue by OnlineCop** [libsdl-org/SDL_mixer#448]
Our [project](https://github.com/OnlineCop/kq-fork) relies on SDL_mixer, which we started using back around the time [revision 2.0.4](https://github.com/libsdl-org/SDL_mixer/tree/release-2.0.4) was the latest. For people setting up our project via [vcpkg](https://github.com/Microsoft/vcpkg), the dependencies resolved fine.

After updating locally to [revision 2.6.1](https://github.com/libsdl-org/SDL_mixer/tree/release-2.6.1) (the latest currently available via vcpkg), configuring CMake emits this warning:

```cmake
CMake Warning at C:/Users/user/source/repos/vcpkg/scripts/buildsystems/vcpkg.cmake:829 (_find_package):
  By not providing "Findsdl2-mixer.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "sdl2-mixer", but CMake did not find one.

  Could not find a package configuration file provided by "sdl2-mixer" with
  any of the following names:

    sdl2-mixerConfig.cmake
    sdl2-mixer-config.cmake

  Add the installation prefix of "sdl2-mixer" to CMAKE_PREFIX_PATH or set
  "sdl2-mixer_DIR" to a directory containing one of the above files.  If
  "sdl2-mixer" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  CMakeLists.txt:12 (find_package)
```

It appears to be looking for `sdl2-mixer-config.cmake` instead of `sdl2_mixer-config.cmake`.

Would this need to be something that needs to be changed by the vcpkg maintainers, something that revision 2.6.2 has already addressed (and I just need to wait for them to point to the latest version), or something I need to change/add on my side (and add to my build steps documentation)?

**Comment by madebr** [comment]
We provide [`SDL2_mixerConfig.cmake`](https://github.com/libsdl-org/SDL_mixer/blob/main/SDL2_mixerConfig.cmake.in) (or [`sdl2_mixer-config.cmake`](https://github.com/libsdl-org/SDL_mixer/blob/main/sdl2_mixer-config.cmake.in) when you're building with autotools).
Bboth are equivalent.

I think [the bug is in your cmake script](https://github.com/OnlineCop/kq-fork/blob/716b3f3f25aaba2e21afb37d054ea7103be83c46/CMakeLists.txt#L12).
You need to do the following instead:
```patch
--- CMakeLists.txt
+++ CMakeLists.txt
@@ -9,7 +9,7 @@
 find_package(Lua REQUIRED)
 find_package(PNG REQUIRED)
 find_package(tinyxml2)
-find_package(sdl2-mixer)
+find_package(SDL2_mixer)
 
 # homebrew doesn't seem to have a FindXXX module for tinyxml2 and SDL_mixer, but vcpkg does,
 # therefore if find_package doesn't work, fall back to pkg-config. There is (usually) no
```

**Comment by OnlineCop** [comment]
Thank you for the suggestion; changing our `sdl2-mixer` to `SDL2_mixer` appears to now let us compile and run:
```diff
--- CMakeLists.txt
+++ CMakeLists.txt
@@ -9,7 +9,7 @@ find_package(SDL2 REQUIRED)
 find_package(Lua REQUIRED)
 find_package(PNG REQUIRED)
 find_package(tinyxml2)
-find_package(sdl2-mixer)
+find_package(SDL2_mixer)

 # homebrew doesn't seem to have a FindXXX module for tinyxml2 and SDL_mixer, but vcpkg does,
 # therefore if find_package doesn't work, fall back to pkg-config. There is (usually) no
@@ -21,8 +21,8 @@ else()
   pkg_check_modules(TINYXML2 REQUIRED tinyxml2)
 endif()

-if(sdl2-mixer_FOUND)
-  set(SDL2_LIBRARIES SDL2::SDL2 SDL2::SDL2main SDL2::SDL2_mixer)
+if(SDL2_mixer_FOUND)
+  set(SDL2_LIBRARIES SDL2::SDL2 SDL2::SDL2main SDL2_mixer::SDL2_mixer)
 else()
   find_package(PkgConfig REQUIRED)
   pkg_check_modules(SDL2_MIXER REQUIRED SDL2_mixer)
```

We're now running into the problem where `Mix_Init(MIX_INIT_MOD)` is returning 0 (with error "MOD support not available" from `Mix_GetError()`), although we (think) we've installed libmodplug with SDL2_mixer.

If this is a separate issue, I'm fine closing this issue (since we were able to get past the compiler error). If one of you have ideas what could be causing modplug to not be loaded/found, I would be happy to provide details/logs if requested.

**Comment by madebr** [comment]
By default, third-party libraries (modplug) are dynamically loaded (with `GetProcAddress`).
So you must make sure your executable/SDL2 is able to find`modplug1.dll` (not sure about the actual filename).
Microsoft provides [this documentation](https://learn.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-search-order#standard-search-order-for-desktop-applications) for Windows.

I think you can add paths by using the `PATH` environment variable, or by making sure all dll's are put in the same folder as your executable.

I don't know how you can do this with vcpkg though.

**Comment by madebr** [comment]
Closing this issue as the original issue has been resolved.
