### ISSUE TITLE
CMake: Native MIDI for macOS: frameworks are added as link_options instead of as link_libraries

### ISSUE THREAD

**Issue by maxmitti** [libsdl-org/SDL_mixer#453]
With CMake under macOS, the frameworks needed for native MIDI are added as link_options instead of linked with target_link_libraries here: https://github.com/libsdl-org/SDL_mixer/blob/main/CMakeLists.txt#L728

This leads to the issue, that the frameworks are not exported into the CMake library configuration files, which leads to undefined references when linking to a static build of SDL2_mixer.

In SDL2, frameworks are linked with target_link_libraries, which seems to fix this problem.
See for example here:

- https://github.com/libsdl-org/SDL/blob/main/CMakeLists.txt#L2148
- https://github.com/libsdl-org/SDL/blob/main/CMakeLists.txt#L3114

**Comment by madebr** [comment]
I opened https://github.com/libsdl-org/SDL_mixer/pull/455 to address this.

Thanks for letting us know about this issue!
