### ISSUE TITLE
Incorrect documentation for Mix_FadeOutChannel

### ISSUE THREAD

**Issue by svanimpe** [libsdl-org/SDL_mixer#456]
The documentation for this function says it returns 0 on success, which isn't the case. This tripped me up for a while.

**Comment by sezero** [comment]
So, `the number of channels touched, 0 if none.` would be a proper description?

**Comment by svanimpe** [comment]
The documentation for `Mix_FadeOutMusic` phrases this as "scheduled to fade", so perhaps this should be "the number of channels scheduled to fade"?

**Comment by sezero** [comment]
> The documentation for `Mix_FadeOutMusic` phrases this as "scheduled to fade", so perhaps this should be "the number of channels scheduled to fade"?

Sounds better I guess. @slouken, @icculus?

**Comment by slouken** [comment]
Sure, sounds good.

**Comment by sezero** [comment]
OK, pushed https://github.com/libsdl-org/SDL_mixer/commit/6dd56a7cbf3efe4b5a4ac86ab47771a9f2ca5a8c
