### ISSUE TITLE
Sample programs don't call Mix_Init()

### ISSUE THREAD

**Issue by genpfault** [libsdl-org/SDL_mixer#464]
The [`playmus.c`](https://github.com/libsdl-org/SDL_mixer/blob/release-2.6.2/playmus.c) and [`playwave.c`](https://github.com/libsdl-org/SDL_mixer/blob/release-2.6.2/playwave.c) sample programs don't call [`Mix_Init()`](https://github.com/libsdl-org/SDL_mixer/blob/release-2.6.2/include/SDL_mixer.h#L118-L180), seemingly in violation of [the API documentation](https://github.com/libsdl-org/SDL_mixer/blob/release-2.6.2/include/SDL_mixer.h#L121-L123) (emphasis mine):

> This function loads dynamic libraries that SDL_mixer needs, and prepares them for use.  **This must be the first function you call in SDL_mixer**, and if it fails you should not continue with the library.

Are the samples wrong?  Is the documentation wrong?  Something else?

**Comment by slouken** [comment]
Yeah, I don't think that's correct. @icculus?

**Comment by icculus** [comment]
Hmm, Mix_Init() only configures music format stuff, and Mix_LoadMusic_RW() will do it for you anyhow. What's the value of having Mix_Init() at all, then? To know if a certain format is unsupported up front?

**Comment by icculus** [comment]
(We can change the "you must call this first" language in any case, since that's clearly not true.)

**Comment by slouken** [comment]
> What's the value of having Mix_Init() at all, then? To know if a certain format is unsupported up front?

Yep.
