### ISSUE TITLE
Mpg123 cannot be compiled in Android

### ISSUE THREAD

**Issue by baidwwy** [libsdl-org/SDL_mixer#474]
Maybe mpg123. h does not match

Use libmpg123.pc.in OK

**Comment by madebr** [comment]
What build system are you using?
What commands are you executing?
Please provide a reproducer.

Relatively recent, I made sure building SDL_mixer built fine with CMake for all 4 Android architectures.

**Comment by baidwwy** [comment]
I don't use CMake, I use Visual Studio, and I don't use asm
such as [android/mpg123.h](https://github.com/libsdl-org/mpg123/blob/v1.29.3-SDL/android/mpg123.h)  no  def MPG123_FLOAT_FALLBACK
https://github.com/libsdl-org/mpg123/blob/5475987f8fb303daf692f3167f5e81506e3c0dcf/src/libmpg123/mpg123.h.in#L294

**Comment by madebr** [comment]
Can you try https://github.com/libsdl-org/mpg123/commit/21471781893f9a615b1d6ffeab435955a51214c6?

**Comment by baidwwy** [comment]
> Can you try [libsdl-org/mpg123@2147178](https://github.com/libsdl-org/mpg123/commit/21471781893f9a615b1d6ffeab435955a51214c6)?

It's working

**Comment by madebr** [comment]
Thanks, fixed for sdl2_mixer in https://github.com/libsdl-org/SDL_mixer/commit/267a198f96d3b8a41f0b46063e84eda6a2e66f03
