### ISSUE TITLE
Static linking issues with libmpg123

### ISSUE THREAD

**Issue by maxmitti** [libsdl-org/SDL_mixer#486]
Similar to #451 there is also an issue with libmpg123.
The target that is generated by libmpg123’s CMakeLists.txt is called `MPG123::libmpg123`.
Perhaps it would make sense to fix it similarly to #454.

**Comment by madebr** [comment]
Does #487 fix your issue?
I also lower cases the `Findmpg123.cmake` module for compatibility with `mpg123-config.cmake` installed by mpg123.

**Comment by maxmitti** [comment]
Yes. :)
