### ISSUE TITLE
Mix_GetMusicPosition, Mix_FFMusic, Mix_RewMusic

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL_mixer#5]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [patch.diff (patch.diff, text/plain, 2006-01-27 02:25:02 +0000, 1204 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=44)

**Reported in version:** unspecified
**Reported for operating system, platform:** All, All

# Comments on the original bug report:

On 2006-01-27 02:24:38 +0000, Sam Lantinga wrote:

> Date: Sun, 23 May 2004 15:39:33 -0300
> From: Emmanuel NM <emmanuelnm@softhome.net>
> Subject: [SDL] SDL_Mixer - [Patch]  A couple of new functions
> 
> Hi  everyone,
> 
> I implemented 3 functions for the SDL_mixer library,  in the file music.c
> 
>     Mix_GetMusicPosition()  - Returns the current position in seconds.
>     Mix_FFMusic(seconds) -  Fast Forward in seconds from the current
> position. Only for MP3 and OGG
>     Mix_RewMusic(seconds) - Rewind in seconds from the current position.
> Only for MP3 and OGG.
> 
> apply the patch with :    "patch music.c patch.diff".
> 
> Sorry about my English.
> Let me know what you think

On 2006-01-27 02:25:02 +0000, Sam Lantinga wrote:

> Created attachment 44
> patch.diff

On 2006-01-27 11:23:28 +0000, Ryan C. Gordon wrote:

> 
> Setting Sam as "QA Contact" on all bugs (even resolved ones) so he'll definitely be in the loop to any further discussion here about SDL.
> 
> --ryan.
> 
> 

On 2009-10-03 02:03:00 +0000, Sam Lantinga wrote:

> These functions aren't as precise as you might expect, but we might be able to use SDL_GetTicks() to improve precision.
> 
> Thanks!

**Comment by slouken** [comment]
`Mix_SetMusicPosition()` and `Mix_GetMusicPosition()` have been implemented for this functionality.
