### ISSUE TITLE
SDL Mixer API namespace consistency

### ISSUE THREAD

**Issue by sbhutch** [libsdl-org/SDL_mixer#505]
The SDL and SDL image APIs capitalize the namespace prefix:

- SDL_Init
- IMG_Init

The SDL mixer and SDL net APIs do not:

- Mix_Init
- Net_Init

Unless this was deliberate, the transition to SDL3 would be a great time to make these APIs consistent.

**Comment by Nhalrath** [comment]
+1 for this...

**Comment by slouken** [comment]
I don't think we're going to change that at this point. Thanks for the feedback!

**Comment by slouken** [comment]
Yep :)
