### ISSUE TITLE
Document website unavaliable.

### ISSUE THREAD

**Issue by Seng-Jik** [libsdl-org/SDL_mixer#509]
http://jcatki.no-ip.org/SDL_mixer/ is unavaliable.

**Comment by madebr** [comment]
Currently, documentation of SDL2_mixer is available at https://wiki.libsdl.org/SDL2_mixer/FrontPage.
Looks like the url you've posted was [last indexed in 2012 by archive.org](https://web.archive.org/web/20120415000000*/http://jcatki.no-ip.org:8080/SDL_mixer/SDL_mixer.html), and was for SDL_mixer 1.2, which is not maintained anymore.
