### ISSUE TITLE
Crash when playing a looped FLAC track

### ISSUE THREAD

**Issue by rfomin** [libsdl-org/SDL_mixer#511]
File: [d_e1m3.zip](https://github.com/libsdl-org/SDL_mixer/files/11217941/d_e1m3.zip) from boosted music pack on [sc55.duke4.net](https://sc55.duke4.net/games.php#doom)

It crashes at looping point, tested with SDL2 branch `playmus` program: `playmus -l d_e1m3.flac`

**Comment by mikeday0** [comment]
I think this might be the fix:

```diff
diff --git a/src/codecs/music_drflac.c b/src/codecs/music_drflac.c
index 9e2336ac..4878b2ea 100644
--- a/src/codecs/music_drflac.c
+++ b/src/codecs/music_drflac.c
@@ -281,7 +281,7 @@ static int DRFLAC_GetSome(void *context, void *data, int bytes, SDL_bool *done)
     if (amount > 0) {
         if (music->loop && (music->play_count != 1) &&
             ((Sint64)music->dec->currentPCMFrame >= music->loop_end)) {
-            amount -= (music->dec->currentPCMFrame - music->loop_end) * sizeof(drflac_int16) * music->channels;
+            amount -= (music->dec->currentPCMFrame - music->loop_end);
             music->loop_flag = SDL_TRUE;
         }
         if (SDL_AudioStreamPut(music->stream, music->buffer, (int)amount * sizeof(drflac_int16) * music->channels) < 0) {
```

**Comment by sezero** [comment]
> I think this might be the fix:
> 
> ```diff
> diff --git a/src/codecs/music_drflac.c b/src/codecs/music_drflac.c
> index 9e2336ac..4878b2ea 100644
> --- a/src/codecs/music_drflac.c
> +++ b/src/codecs/music_drflac.c
> @@ -281,7 +281,7 @@ static int DRFLAC_GetSome(void *context, void *data, int bytes, SDL_bool *done)
>      if (amount > 0) {
>          if (music->loop && (music->play_count != 1) &&
>              ((Sint64)music->dec->currentPCMFrame >= music->loop_end)) {
> -            amount -= (music->dec->currentPCMFrame - music->loop_end) * sizeof(drflac_int16) * music->channels;
> +            amount -= (music->dec->currentPCMFrame - music->loop_end);
>              music->loop_flag = SDL_TRUE;
>          }
>          if (SDL_AudioStreamPut(music->stream, music->buffer, (int)amount * sizeof(drflac_int16) * music->channels) < 0) {
> ```

This patch looks good to me. @slouken, @icculus ?

**Comment by sezero** [comment]
OK, the patch is in: Fixed in both SDL2 and main (SDL3) branches.

Thanks.

**Comment by mikeday0** [comment]
Would it be possible to get a 2.6.x bugfix release which has this patch applied? Thanks!

**Comment by slouken** [comment]
I'm planning a 2.8 release soon with this patch.
