### ISSUE TITLE
SDL_mixer 1.2.7 for Win x64

### ISSUE THREAD

**Issue by qrp73** [libsdl-org/SDL_mixer#514]
Hi, I know, this is a new version of SDL_mixer, but I don't know where to ask about SDL_mixer 1.2, so maybe someone can help me.

I'm tried to compile SDL_mixer 1.2.7 (source code downloaded here: url: https://www.libsdl.org/projects/mixer/release/SDL_mixer-1.2.7.zip). It take some time to add x64 platform and to fix build path, and after all, build is done - I got SDL_mixer.dll for x64 platform and tried to run my app. But for some unknown reason it raises Access violation exception on a first attempt to call ```Mix_OpenAudio(22050, AUDIO_S16, 2, 1024)```.

The code works ok for x86 platform with SDL_mixer 1.2.7 compiled for x86 platform. 
So, it looks that x64 version of SDL_mixer 1.2.7 doesn't works properly. But I changed project files in order to add x64 platform, because it was missing from original SDL_mixer 1.2.7 sources, so I'm not sure if there is some my mistake.

And I'm not sure, does SDL_mixer 1.2.7 supports x64 platform on windows?

**Comment by aronson** [comment]
Hi there, I build a lot of these old libraries for games and took a look. I'm going to assume you're building on Windows x64 with Visual Studio, as you didn't specify.

I see that release 1.2.12 features an x64 target within the VisualC project. I built it and loaded it no problem in an example project with VS 2022. I suggest using that release as it's the latest for the 1.2 milestone. I wouldn't try using specifically 1.2.7 unless you have a particular reason.

**Comment by qrp73** [comment]
Where did you get source code for 1.2.12? 

The latest published code that I see is 1.2.7. I'm using this source: https://www.libsdl.org/projects/mixer/release/

**Comment by madebr** [comment]
I had to use google to find this URL: https://www.libsdl.org/release/

**Comment by madebr** [comment]
I had to use google: https://www.libsdl.org/projects/SDL_mixer/release/

**Comment by aronson** [comment]
[Here you go](https://www.libsdl.org/projects/SDL_mixer/release/)

**Comment by qrp73** [comment]
your link is SDL2-mixer-2. 
I need SDL_mixer-1.2, this is different project.

I know that this repository is for SDL2-mixer-2, but unfortunately there is no repository for old SDL_mixer-1.2, so there is no place to ask help with it. This is why I'm asking it here
