### ISSUE TITLE
the Xcode project needs updating

### ISSUE THREAD

**Issue by sezero** [libsdl-org/SDL_mixer#565]
Xcode project needs updating for both SDL2 and SDL3 branches:

- wavpack option should be enabled: `MUSIC_WAVPACK` must be defined

- A wavpack project must be created, like the others, and must be
  integrated in the main SDL_mixer project (like the others..)

A job for @slouken (can't do myself.)

**Comment by sezero** [comment]
@slouken: wavpack.framework seems to be missing in prerelease 2.7.2 dmg

**Comment by slouken** [comment]
Fixed for release, thanks!

**Comment by sezero** [comment]
I minorly updated our vendored libgme (game-music-emu): the submodule should point to commit cdd021507518162a4884898bbac85cbd32ed7a77 -- please make sure your copies are updated.

**Comment by slouken** [comment]
Please don't do that when we have a release candidate pending unless it's a critical fix. If it's not necessary for release, can you please revert until next week?

**Comment by sezero** [comment]
> Please don't do that when we have a release candidate pending unless it's a critical fix. If it's not necessary for release, can you please revert until next week?

It is a build fix: https://github.com/libsdl-org/game-music-emu/commit/cdd021507518162a4884898bbac85cbd32ed7a77
If you're sure, yes I can easily revert

**Comment by slouken** [comment]
Okay, that looks fine, but in general once a pre-release tag is added to a project, that code is frozen except for critical bug fixes until release. We don't want to introduce any regressions between the time the public tries out the release candidate and the final release.
