### ISSUE TITLE
SDL2MIXER_OPUS_SHARED doesn't work.

### ISSUE THREAD

**Issue by jinfeihan57** [libsdl-org/SDL_mixer#567]
I can't chang SDL2MIXER_OPUS_SHARED manually.
![image](https://github.com/libsdl-org/SDL_mixer/assets/38484902/8d135ab1-e3bc-4968-a95d-735cf6985cce)

if : SDL2MIXER_OPUS ON 
then : SDL2MIXER_OPUS_SHARED ON

I want use SDL2MIXER_OPUS, But not dynamic load way. 
How should I do? 
Or if there's any information I missed？

**Comment by madebr** [comment]
Just configure with `-DSDL2MIXER_OPUS_SHARED=OFF`.
You need to read the [`cmake_dependent_option`](https://cmake.org/cmake/help/latest/module/CMakeDependentOption.html#command:cmake_dependent_option) command as:

```
cmake_dependent_option(<option-name> <doc-string> <default-value-overridable-by-user> <condition-for-user-value-to-be-used> <forced-value-when-condition-is-false>)
```
