### ISSUE TITLE
static build SDL2MIXER_SAMPLES error

### ISSUE THREAD

**Issue by jinfeihan57** [libsdl-org/SDL_mixer#568]
Version 2.6.3
build option：
    set(SDL2MIXER_VENDORED ON)
    set(SDL2MIXER_INSTALL OFF)
    set(SDL2MIXER_DEPS_SHARED OFF)
![2023-10-12_224639](https://github.com/libsdl-org/SDL_mixer/assets/38484902/b24d2aef-e423-4de8-ad0d-3d562417ff0c)

**Comment by jinfeihan57** [comment]
The above log shows compilation errors in the MSYS2 UCRT64 environment.
Cmake option settings：
![image](https://github.com/libsdl-org/SDL_mixer/assets/38484902/640a67a5-e5c5-4b1e-bf04-e7bf1593221e)

The following is compiled using MSYS2 CLANG64
MSYS2 clang64 build ENV:
![image](https://github.com/libsdl-org/SDL_mixer/assets/38484902/75b28db2-7a6a-4542-99cb-194ba8624e8a)
.rsp file:
![image](https://github.com/libsdl-org/SDL_mixer/assets/38484902/619fd9c0-b15e-441a-b496-18e546bd6286)

**Comment by jinfeihan57** [comment]
If I set(SDL2MIXER_DEPS_SHARED ON), use Dynamically load modplug. It will compiler OK. 
But just because the compilation is successful does not indicate that modplug is available. 
and I want use static link,not dynamic load.

**Comment by madebr** [comment]
Thanks for the logs.
Fixed in https://github.com/libsdl-org/SDL_mixer/commit/32381dfc650573f59adb974582a24644496c3004 and https://github.com/libsdl-org/libmodplug/commit/1e03298678882ed986194be761fdf286db98e2fa
You can fix it in your project by adding the following _after_ `add_subdirectory(SDL_mixer)`
```cmake
if(TARGET modplug)
    target_compile_definitions(modplug PUBLIC MODPLUG_STATIC)
endif()
```
