### ISSUE TITLE
SDL3 + Android = error: undefined symbol: Mix_HookMusicFinished

### ISSUE THREAD

**Issue by AntTheAlchemist** [libsdl-org/SDL_mixer#569]
I'm not able to use `Mix_HookMusicFinished` in the latest SDL3 source when building for Android. It worked with SDL2, so I'm not sure at what stage this bug appeared. Very odd, but then I noticed that `Mix_HookMusicFinished` is not listed in SDL_mixer.sym, might this be the problem? I can use other `Mix_*` methods without a problem.

**Comment by sezero** [comment]
Should be fixed as of https://github.com/libsdl-org/SDL_mixer/commit/d9d4f145726c08d4b60ffd903c5f1d6644da4815: Please confirm.

**Comment by AntTheAlchemist** [comment]
@sezero That's fixed it, thanks!
