### ISSUE TITLE
Can not set channel volume louder than music

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL_mixer#57]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [modified playwave for example. (playwave.c, text/plain, 2009-10-10 20:26:17 +0000, 12783 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=407)
* [wav file I used for testing (whoosh.wav, application/octet-stream, 2009-10-10 20:27:04 +0000, 13516 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=408)

**Reported in version:** 1.2.8
**Reported for operating system, platform:** Windows Vista, x86

# Comments on the original bug report:

On 2009-05-29 00:33:02 +0000, Ars wrote:

> When music is playing and its volume is set, say, to 40, then channel sound is being played not louder than 40, even if SDL_Volume is set to bigger value.
> 
> Issue is seen with midi and mp3 samples.

On 2009-10-10 20:26:17 +0000, Ryan C. Gordon wrote:

> Created attachment 407
> modified playwave for example.
> 
> I can't reproduce this in the latest svn. Here's a modified version of playwave that loops a .wav file until you hit ctrl-c while playing an mp3, fading the mp3's volume in and out every few seconds.
> 
> Look for "/home/icculus" in the source and supply your own mp3 or midi.
> 
> The .wav file is attached here. Notice that the volume doesn't change, and it never prints out a warning that the volume is incorrect (so the mixer thinks the volume is correct AND it actually is).
> 
> If you have a better test case that triggers this bug, please post it here, but I can't do more with the information I have.
> 
> --ryan.

On 2009-10-10 20:27:04 +0000, Ryan C. Gordon wrote:

> Created attachment 408
> wav file I used for testing

On 2011-12-31 11:02:56 +0000, Sam Lantinga wrote:

> No response in a couple years, closing this out for now.

**Comment by scarsty** [comment]
I also found it in the newest SDL3 mixer
