### ISSUE TITLE
Relationship between SDL_mixer and SDL_sound is unclear

### ISSUE THREAD

**Issue by Splendide-Imaginarius** [libsdl-org/SDL_mixer#572]
SDL_mixer and @icculus's SDL_sound seem to have nontrivial overlap. I can't find any documentation on what the relationship between the two projects is, and how one would pick between them for a given use case. Is there any such documentation that I've missed? Best I can find is a comment in #95 from @slouken indicating that sometime in 2011 there was an intent to merge the two projects; I suspect a lot has happened since then.

**Comment by slouken** [comment]
SDL_sound is designed to load audio files, essentially SDL_image for audio. SDL_mixer does that and also allows mixing with various effects. We were intending to have SDL_mixer use SDL_sound for audio loading at one point, but I think it's a probably a moot point these days.
