### ISSUE TITLE
Add optional GME DLL for Windows release

### ISSUE THREAD

**Issue by slouken** [libsdl-org/SDL_mixer#587]
The macOS release has optional gme and wavpack frameworks, and the Windows release has optional wavpack DLL, but is missing the GME DLL.

Can you build and test x86 and x64 GME DLLs for the release?

**Comment by sezero** [comment]
OK, I will build today. But they will have to statically link to libstc++ yes? They will have bloated sizes..

**Comment by sezero** [comment]
OK, added them.

Note that gme option is disabled by default in both autotools and cmake. Don't know how it is in msvc project.

Closing.
