### ISSUE TITLE
Replace SDL_RWops with SDL_IOStream for SDL3

### ISSUE THREAD

**Issue by M2-TE** [libsdl-org/SDL_mixer#597]
SDL3 upstream has replaced SDL_RWops with SDL_IOStream as described in this [SDL3 PR](https://github.com/libsdl-org/SDL/pull/9254). 
This change affects all functions with the _RW suffix and could temporarily be alleviated by not compiling them via a macro flag or adjusting them according to the new SDL_IOStream.

**Comment by slouken** [comment]
Yep, we'll update the SDL satellite libraries for the new API over the next few days.
