### ISSUE TITLE
`stb_vorbis_open_IO` implicitly declared, compiler suggests `stb_vorbis_open_io`

### ISSUE THREAD

**Issue by Semphriss** [libsdl-org/SDL_mixer#599]
At [this line](https://github.com/libsdl-org/SDL_mixer/blob/e98d0a9d10364ab6f9e6fc2c19dbe41fff71d0ab/src/codecs/music_ogg_stb.c#L183C1-L183C58), I'm getting:

```
warning: implicit declaration of function 'stb_vorbis_open_IO'; did you mean 'stb_vorbis_open_io'?
```

and a corresponding linker error; is this a typo or a problem on my end?

I'm using `SDL2MIXER_VENDORED=ON`, if that plays.

**Comment by slouken** [comment]
It's a typo, thanks!
