### ISSUE TITLE
Pretty much all function declarations say "Available since SDL Mixer 3.0" even though they were implemented in version 2.8 or older.

### ISSUE THREAD

**Issue by Panjaksli** [libsdl-org/SDL_mixer#604]
Is that a oversight ? Just confused me a little when reading the header definition in current repo vs in 2.8 release. Made me think for a while that I cannot do any of the stuff from examples in 2x releases.

**Comment by Starbuck5** [comment]
I'm pretty sure this is intended behavior. All the SDL libraries are like that. They're just wiping the changelog every major version, conceptually.
