### ISSUE TITLE
gcc -Wall -Werror, build error

### ISSUE THREAD

**Issue by medaminben** [libsdl-org/SDL_mixer#614]
Hey folks
https://github.com/libsdl-org/SDL_mixer/blob/4ed68d19e98d7eecdd10eb15166ffa2d8a0991ef/src/codecs/stb_vorbis/stb_vorbis.h#L3769-L3769
building with gcc 13.1 flagged as -Wall -Werror throws:

> comparison of integer expressions of different signedness: 'long long unsigned int' and 'int' [-Werror=sign-compare]

a cast takes it out:
` if ((int)(INT_MAX / sizeof(char*)) < f->comment_list_length)`
can someone fix it please

**Comment by sezero** [comment]
I don't have gcc13 available, but my gcc14 warns only when using `-W` or `-Wextra`. Pushing a fix shortly.

**Comment by sezero** [comment]
Fixed.
