### ISSUE TITLE
/MD

### ISSUE THREAD

**Issue by 1vanK** [libsdl-org/SDL_mixer#621]
SDL uses /MT option by default:

```
if(MSVC)
  dep_option(SDL_STATIC_VCRT "Use /MT for static VC runtimes" ON "NOT WINDOWS_STORE" OFF)
  ...
```

SDL_mixer uses /MD option.

This cause warning:

```
LINK : warning LNK4098: defaultlib 'LIBCMTD' conflicts with use of other libs; use /NODEFAULTLIB:library
```

**Comment by madebr** [comment]
Let's remove `SDL_STATIC_VCRT` form SDL, and return the control of `CMAKE_C_FLAGS` and `CMAKE_MSVC_RUNTIME_LIBRARY` to the users.
