### ISSUE TITLE
[SDL2] CI macOS runner failing in release-2.8.x, but succeeding in SDL2

### ISSUE THREAD

**Issue by sezero** [libsdl-org/SDL_mixer#629]
See: https://github.com/libsdl-org/SDL_mixer/actions/runs/10386371038/job/28757509706

CC: @madebr

**Comment by madebr** [comment]
https://github.com/libsdl-org/SDL_mixer/commit/0c32440b739b5c34330901665e22128d290aaa7a fixes it

Older CMake versions don't know about Apple silicon
