### ISSUE TITLE
VisualC: correct OGG_DYNAMIC

### ISSUE THREAD

**Issue by madebr** [libsdl-org/SDL_mixer#639]
https://github.com/libsdl-org/SDL_mixer/blob/e32ba24f21208c7a20328dbb5111a237495514c8/VisualC/SDL_mixer.vcxproj#L114
Is this correct?
Shouldn't it be `OGG_DYNAMIC="libogg-0.dll"?

Please don't fix this in git, I'll fix this when I "dump" the release scripts ;)

**Comment by sezero** [comment]
> https://github.com/libsdl-org/SDL_mixer/blob/e32ba24f21208c7a20328dbb5111a237495514c8/VisualC/SDL_mixer.vcxproj#L114
> 
> Is this correct?

Yes

> Shouldn't it be `OGG_DYNAMIC="libogg-0.dll"?

No. (We import from libvorbisfile which happens to piggy-back to libvorbis which in turn makes use of libogg.)

**Comment by sezero** [comment]
P.S.: It's just that `OGG_DYNAMIC` name is just misleading, that's all.

**Comment by madebr** [comment]
Thanks! I see CMake is also doing what you described.

**Comment by madebr** [comment]
When defining `OGG_USE_STB`, it will use stb_vorbis to load ogg files.
