### ISSUE TITLE
Use SDL_Process for CMD codec

### ISSUE THREAD

**Issue by madebr** [libsdl-org/SDL_mixer#640]
I just noticed the `music_CMD` "codec" does not build with MinGW (probably also not with MSVC).
So perhaps this is a good opportunity to either rewrite it on top of SDL_Process, or remove the "codec".

**Comment by sezero** [comment]
Do we still want cmd in SDL3_mixer?

**Comment by slouken** [comment]
Let's go ahead and remove it.

**Comment by Wohlstand** [comment]
Hey, wait! This cmd-music thing is already used by the several stuff like some games. This feature is UNIX-only, and it was never supposed to work on Windows and macOS (for macOS there was my attempts to fix it, but not success, so, it works on Linux and xBSD systems), and on several other platforms like Haiku and Android it doesn't work too. I used it inside these games to pass my custom-built players from libADLMIDI or libOPNMIDI to play MIDI music using some of these clunky engines.

Anyway, by myself I don't care about this thing so much, but I keep it on the MixerX side just in a case, but I build it for only few platforms like UNIX-like systems with exceptions.

**Comment by sezero** [comment]
> Hey, wait! This cmd-music thing is already used by the several stuff

It's removed from SDL3_mixer only. SDL2_mixer isn't touched for it.

**Comment by Wohlstand** [comment]
That's right, anyway, once the stable ABI of SDL3 will be released, I'll make the SDL3 version of the MixerX quickly. But for now, I just tracking the development process itself.
