### ISSUE TITLE
Gitignore deleted (by mistake?)

### ISSUE THREAD

**Issue by Starbuck5** [libsdl-org/SDL_mixer#651]
Hello,

I just booted up this project to build in Visual Studio and saw a lot of unstaged changes added to my repository.

I thought, oh, maybe this needs to be added to the gitignore, then I noticed there wasn't a gitignore.

This repository used to have a gitignore. I tracked its deletion to https://github.com/libsdl-org/SDL_mixer/commit/4b7a04db883e1174eb8e7b63838a01c4dea1c003#diff-bc37d034bad564583790a46f19d807abfe519c5671395fd494d8cce506c42947 . Presumably deleted by accident.

**Comment by madebr** [comment]
Oops! I restored it in d4eba31e4ac23a81fffad02e91b17dcb2449a2cb

Thanks for telling us!
