### ISSUE TITLE
Mix_Volume fails to set volume on channel 0 playing a repeating sound

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL_mixer#93]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 1.2.11
**Reported for operating system, platform:** Linux, x86

# Comments on the original bug report:

On 2011-04-05 15:46:13 +0000,  wrote:

> I have encountered an issue with Mix_Volume. It fails to set the volume value for the first assigned channel (0) after calling Mix_PlayChannel(-1,chunk,-1).
> 
> The problem is fixed if adding Mix_ReserveChannels(1) before trying to play anything. Mix_VolumeChunk() fails in the same way.

On 2011-12-31 11:39:15 +0000, Ryan C. Gordon wrote:

> 
> Bumping priority on a few SDL_mixer bugs. This is just so we know to look at them for an upcoming release, but once we look at them more closely, we may decide to flag them as WONTFIX or push them back to a later release, so don't take this change in priority as any promise of anything, yet.  :)
> 
> --ryan.

**Comment by slouken** [comment]
This appears to be fixed. The variable num_channels is initialized to MIX_CHANNELS (8), and is checked in Mix_Volume().
Please reopen this if you're seeing this bug with a different use case than I'm looking at.
